#this file contains transition sequences between various patterns. I have added
#   transitions as I've needed them, so not all transitions work along all axes,
#   between all patterns, etc.

#import points list, time.sleep, and fundamental plotting functions
from LEDcubeCore import points
from time import sleep
from plot import *

#right now, all transitions are run as a single function, which is a TERRIBLE
#   means of execution. I will probably restructure this at some point.
def transition(name, hasToBeHere, speed):
    if name == "start-xbounce":
        plot(0, 0, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 1)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 2)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 2, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
    elif name == "xbounce-ybounce":
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 3)
        plotFill(1, 1, 0, 1, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(3, 3, 0, 3, 3, 3)
        plotFill(2, 2, 0, 2, 2, 3)
        plotFill(1, 1, 0, 1, 1, 3)
        plotFill(0, 0, 0, 0, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 3)
        plotFill(1, 1, 0, 3, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 3)
        sleep(speed)
    elif name == "ybounce-zbounce":
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 1, 1)
        plotFill(0, 2, 2, 3, 2, 2)
        plotFill(0, 3, 3, 3, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 3, 1)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 3, 0)
        sleep(speed)
    elif name == "zbounce-xbounce":
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 3, 3, 1)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 1, 3, 1)
        plotFill(2, 0, 2, 2, 3, 2)
        plotFill(3, 0, 3, 3, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 1, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
    elif name == "ybounce-xbounce":
        plotFill(0, 0, 0, 0, 0, 3)
        plotFill(1, 1, 0, 1, 1, 3)
        plotFill(1, 0, 0, 1, 0, 3, 0)
        sleep(speed)
        plotFill(0, 0, 0, 0, 0, 3)
        plotFill(1, 1, 0, 1, 1, 3)
        plotFill(2, 2, 0, 2, 2, 3)
        plotFill(3, 3, 0, 3, 3, 3)
        plotFill(1, 0, 0, 1, 0, 3, 0)
        plotFill(2, 0, 0, 3, 1, 3, 0)
        plotFill(3, 2, 0, 3, 2, 3, 0)
        sleep(speed)
        plotFill(0, 0, 0, 0, 0, 3)
        plotFill(1, 1, 0, 1, 3, 3)
        plotFill(2, 0, 0, 3, 3, 3, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 3)
        sleep(speed)
    elif name == "xbounce-yspin":   #yspin? because it's fun, that's y
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 1, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 1, 3, 1)
        plotFill(2, 0, 2, 2, 3, 2)
        plotFill(3, 0, 3, 3, 3, 3)
        sleep(speed)
        fullcube(0)
    elif name == "ybounce-xspin":
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 1, 1)
        plotFill(0, 2, 2, 3, 2, 2)
        plotFill(0, 3, 3, 3, 3, 3)
        sleep(speed)
    elif name == "yspin-xbounce":
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 0)
        plotFill(1, 0, 1, 1, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed*2)
    elif name == "xspin-ybounce":
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        plotFill(0, 1, 1, 3, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 3)
        sleep(speed)
    elif name == "xbounce-end":
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 2, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 2)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 0, 1)
        sleep(speed)
        fullcube(0)
        plot(0, 0, 0)
        sleep(speed)
        plot(0, 0, 0, 0)
    elif name == "zbounce-woopwoop":
        fullcube(0)
        plotFill(0, 0, 0, 3, 2, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 1, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 2, 0, 0)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 1, 0, 0)
        sleep(speed)
        plot(0, 0, 0)
        sleep(speed)
    elif name == "woopwoop-zbounce":
        fullcube(0)
        wireframe(0, 4)
        plot(1, 1, 3)
        sleep(speed)
        plot(2, 2, 3)
        sleep(speed)
        plot(1, 2, 3)
        sleep(speed)
        plot(2, 1, 3)
        sleep(speed)
        fullcube(0)
        wireframe(0, 4)
        plotFill(0, 0, 3, 3, 3, 3, 0)
        plotFill(0, 0, 2, 3, 3, 2)
        sleep(speed)
        fullcube(0)
        wireframe(0, 4)
        plotFill(0, 0, 2, 3, 3, 3, 0)
        plotFill(0, 0, 1, 3, 3, 1)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 3, 3, 0)
        sleep(speed)
    elif name == "ybounce-rain":
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 1, 0, 3, 1, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 2, 0, 3, 2, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 3, 0, 3, 3, 3)
        sleep(speed)
    elif name == "xbounce-spiral":
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
        plotFill(1, 0, 0, 1, 3, 3)
        sleep(speed)
        plotFill(2, 0, 0, 2, 3, 3)
        sleep(speed)
        fullcube()
        sleep(speed*3)
        fullcube(0)
        plotFill(1, 2, 2, 3, 0, 0)
        sleep(speed)
        fullcube(0)
        plotFill(2, 1, 1, 3, 0, 0)
        sleep(speed)
        fullcube(0)
        plot(3, 0, 0)
        sleep(speed)
    elif name == "spiral-xbounce":
        fullcube(0)
        plot(3, 3, 0)
        sleep(speed)
        plotFill(2, 1, 1, 3, 0, 0)
        sleep(speed)
        plotFill(1, 2, 2, 3, 0, 0)
        sleep(speed)
        fullcube()
        sleep(speed*3)
        plotFill(3, 0, 0, 3, 3, 3, 0)
        sleep(speed)
        plotFill(2, 0, 0, 2, 3, 3, 0)
        sleep(speed)
        plotFill(1, 0, 0, 1, 3, 3, 0)
        sleep(speed)
    elif name == "ybounce-yname":
        fullcube(0)
        plotFill(0, 0, 0, 3, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 2, 3, 0, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 3, 3, 0, 3)
        plot(0, 0, 2)
        plot(1, 0, 1)
        plot(2, 0, 2)
        sleep(speed)
    elif name == "yname-rain":
        plotFill(0, 3, 0, 3, 3, 0)
        sleep(speed)
        plotFill(0, 3, 1, 3, 3, 1)
        sleep(speed)
        plotFill(0, 3, 2, 3, 3, 2)
        sleep(speed)
    elif name == "xbounce-xname":
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(1, 0, 0, 1, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(2, 0, 0, 2, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(3, 0, 0, 3, 3, 3)
        sleep(speed)
        plotFill(3, 0, 0, 3, 3, 0)
        sleep(speed)
    elif name == "xname-xbounce":
        plotFill(0, 0, 1, 0, 3, 3)
        sleep(speed)
        fullcube(0)
        plotFill(0, 0, 0, 0, 3, 3)
        sleep(speed)
